/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.ide;

import com.poli.compilador.ide.AbstractCIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CIdeModule extends AbstractCIdeModule {
}
