/*
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCScopeProvider extends DelegatingScopeProvider {
}
