/*
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.parser.antlr;

import com.google.inject.Inject;
import com.poli.compilador.parser.antlr.internal.InternalCParser;
import com.poli.compilador.services.CGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CParser extends AbstractAntlrParser {

	@Inject
	private CGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCParser createParser(XtextTokenStream stream) {
		return new InternalCParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public CGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
