/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arith Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.poli.compilador.c.CPackage#getArithExp()
 * @model
 * @generated
 */
public interface ArithExp extends RelExp
{
} // ArithExp
