/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>break Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.poli.compilador.c.CPackage#getbreakCmd()
 * @model
 * @generated
 */
public interface breakCmd extends Command
{
} // breakCmd
