/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.poli.compilador.c.CFactory
 * @model kind="package"
 * @generated
 */
public interface CPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "c";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.poli.com/compilador/C";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "c";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CPackage eINSTANCE = com.poli.compilador.c.impl.CPackageImpl.init();

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.ProgramImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Definition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__DEFINITION = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.DefinitionImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__VAL = 0;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.FunctionImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 2;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__TIPO = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__COMMANDS = 3;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.DeclarationImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__VAL = DEFINITION__VAL;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TIPO = DEFINITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__NAME = DEFINITION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Asg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__ASG = DEFINITION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = DEFINITION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.CommandImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 4;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__EXP = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.RelExpImpl <em>Rel Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.RelExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getRelExp()
   * @generated
   */
  int REL_EXP = 6;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXP__ARGS = 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXP__VAL = 1;

  /**
   * The number of structural features of the '<em>Rel Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REL_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.ArithExpImpl <em>Arith Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.ArithExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getArithExp()
   * @generated
   */
  int ARITH_EXP = 7;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXP__ARGS = REL_EXP__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXP__VAL = REL_EXP__VAL;

  /**
   * The number of structural features of the '<em>Arith Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXP_FEATURE_COUNT = REL_EXP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.TermImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getTerm()
   * @generated
   */
  int TERM = 8;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__ARGS = ARITH_EXP__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__VAL = ARITH_EXP__VAL;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = ARITH_EXP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.FactorImpl <em>Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.FactorImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getFactor()
   * @generated
   */
  int FACTOR = 9;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__ARGS = TERM__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__VAL = TERM__VAL;

  /**
   * The number of structural features of the '<em>Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_FEATURE_COUNT = TERM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.AtomImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 10;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__ARGS = FACTOR__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__VAL = FACTOR__VAL;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = FACTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.ExpressionImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ARGS = ATOM__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VAL = ATOM__VAL;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = ATOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.lValueImpl <em>lValue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.lValueImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getlValue()
   * @generated
   */
  int LVALUE = 11;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE__ARGS = ATOM__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE__VAL = ATOM__VAL;

  /**
   * The number of structural features of the '<em>lValue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LVALUE_FEATURE_COUNT = ATOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.PointerExpImpl <em>Pointer Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.PointerExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getPointerExp()
   * @generated
   */
  int POINTER_EXP = 12;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTER_EXP__ARGS = LVALUE__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTER_EXP__VAL = LVALUE__VAL;

  /**
   * The feature id for the '<em><b>Ptr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTER_EXP__PTR = LVALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Pointer Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTER_EXP_FEATURE_COUNT = LVALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.LiteralImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 13;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__ARGS = ATOM__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__VAL = ATOM__VAL;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = ATOM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.LogicExpImpl <em>Logic Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.LogicExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getLogicExp()
   * @generated
   */
  int LOGIC_EXP = 14;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__ARGS = EXPRESSION__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__VAL = EXPRESSION__VAL;

  /**
   * The number of structural features of the '<em>Logic Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.AritmExpImpl <em>Aritm Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.AritmExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getAritmExp()
   * @generated
   */
  int ARITM_EXP = 15;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITM_EXP__ARGS = ARITH_EXP__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITM_EXP__VAL = ARITH_EXP__VAL;

  /**
   * The number of structural features of the '<em>Aritm Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITM_EXP_FEATURE_COUNT = ARITH_EXP_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.UnaryExpImpl <em>Unary Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.UnaryExpImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getUnaryExp()
   * @generated
   */
  int UNARY_EXP = 16;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXP__ARGS = FACTOR__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXP__VAL = FACTOR__VAL;

  /**
   * The number of structural features of the '<em>Unary Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXP_FEATURE_COUNT = FACTOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.IDValImpl <em>ID Val</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.IDValImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getIDVal()
   * @generated
   */
  int ID_VAL = 17;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_VAL__ARGS = LVALUE__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_VAL__VAL = LVALUE__VAL;

  /**
   * The number of structural features of the '<em>ID Val</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ID_VAL_FEATURE_COUNT = LVALUE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.IntLitImpl <em>Int Lit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.IntLitImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getIntLit()
   * @generated
   */
  int INT_LIT = 18;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT__ARGS = LITERAL__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT__VAL = LITERAL__VAL;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT__VALOR = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Lit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LIT_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.TrueLitImpl <em>True Lit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.TrueLitImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getTrueLit()
   * @generated
   */
  int TRUE_LIT = 19;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRUE_LIT__ARGS = LITERAL__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRUE_LIT__VAL = LITERAL__VAL;

  /**
   * The number of structural features of the '<em>True Lit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRUE_LIT_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.poli.compilador.c.impl.FalseLitImpl <em>False Lit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.poli.compilador.c.impl.FalseLitImpl
   * @see com.poli.compilador.c.impl.CPackageImpl#getFalseLit()
   * @generated
   */
  int FALSE_LIT = 20;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FALSE_LIT__ARGS = LITERAL__ARGS;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FALSE_LIT__VAL = LITERAL__VAL;

  /**
   * The number of structural features of the '<em>False Lit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FALSE_LIT_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see com.poli.compilador.c.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.Program#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Definition</em>'.
   * @see com.poli.compilador.c.Program#getDefinition()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Definition();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see com.poli.compilador.c.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.Definition#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Val</em>'.
   * @see com.poli.compilador.c.Definition#getVal()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Val();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see com.poli.compilador.c.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.Function#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see com.poli.compilador.c.Function#getTipo()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Tipo();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.poli.compilador.c.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the attribute list '{@link com.poli.compilador.c.Function#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see com.poli.compilador.c.Function#getParams()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Params();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.Function#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see com.poli.compilador.c.Function#getCommands()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Commands();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see com.poli.compilador.c.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.Declaration#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see com.poli.compilador.c.Declaration#getTipo()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Tipo();

  /**
   * Returns the meta object for the attribute list '{@link com.poli.compilador.c.Declaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Name</em>'.
   * @see com.poli.compilador.c.Declaration#getName()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.Declaration#getAsg <em>Asg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Asg</em>'.
   * @see com.poli.compilador.c.Declaration#getAsg()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Asg();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see com.poli.compilador.c.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.Command#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see com.poli.compilador.c.Command#getExp()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.Command#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see com.poli.compilador.c.Command#getCommands()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Commands();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.poli.compilador.c.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.RelExp <em>Rel Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rel Exp</em>'.
   * @see com.poli.compilador.c.RelExp
   * @generated
   */
  EClass getRelExp();

  /**
   * Returns the meta object for the containment reference list '{@link com.poli.compilador.c.RelExp#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see com.poli.compilador.c.RelExp#getArgs()
   * @see #getRelExp()
   * @generated
   */
  EReference getRelExp_Args();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.RelExp#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see com.poli.compilador.c.RelExp#getVal()
   * @see #getRelExp()
   * @generated
   */
  EAttribute getRelExp_Val();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.ArithExp <em>Arith Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Exp</em>'.
   * @see com.poli.compilador.c.ArithExp
   * @generated
   */
  EClass getArithExp();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see com.poli.compilador.c.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Factor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor</em>'.
   * @see com.poli.compilador.c.Factor
   * @generated
   */
  EClass getFactor();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see com.poli.compilador.c.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.lValue <em>lValue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>lValue</em>'.
   * @see com.poli.compilador.c.lValue
   * @generated
   */
  EClass getlValue();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.PointerExp <em>Pointer Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pointer Exp</em>'.
   * @see com.poli.compilador.c.PointerExp
   * @generated
   */
  EClass getPointerExp();

  /**
   * Returns the meta object for the containment reference '{@link com.poli.compilador.c.PointerExp#getPtr <em>Ptr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ptr</em>'.
   * @see com.poli.compilador.c.PointerExp#getPtr()
   * @see #getPointerExp()
   * @generated
   */
  EReference getPointerExp_Ptr();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see com.poli.compilador.c.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.LogicExp <em>Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Exp</em>'.
   * @see com.poli.compilador.c.LogicExp
   * @generated
   */
  EClass getLogicExp();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.AritmExp <em>Aritm Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aritm Exp</em>'.
   * @see com.poli.compilador.c.AritmExp
   * @generated
   */
  EClass getAritmExp();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.UnaryExp <em>Unary Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Exp</em>'.
   * @see com.poli.compilador.c.UnaryExp
   * @generated
   */
  EClass getUnaryExp();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.IDVal <em>ID Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ID Val</em>'.
   * @see com.poli.compilador.c.IDVal
   * @generated
   */
  EClass getIDVal();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.IntLit <em>Int Lit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Lit</em>'.
   * @see com.poli.compilador.c.IntLit
   * @generated
   */
  EClass getIntLit();

  /**
   * Returns the meta object for the attribute '{@link com.poli.compilador.c.IntLit#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see com.poli.compilador.c.IntLit#getValor()
   * @see #getIntLit()
   * @generated
   */
  EAttribute getIntLit_Valor();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.TrueLit <em>True Lit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>True Lit</em>'.
   * @see com.poli.compilador.c.TrueLit
   * @generated
   */
  EClass getTrueLit();

  /**
   * Returns the meta object for class '{@link com.poli.compilador.c.FalseLit <em>False Lit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>False Lit</em>'.
   * @see com.poli.compilador.c.FalseLit
   * @generated
   */
  EClass getFalseLit();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CFactory getCFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.ProgramImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__DEFINITION = eINSTANCE.getProgram_Definition();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.DefinitionImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__VAL = eINSTANCE.getDefinition_Val();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.FunctionImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__TIPO = eINSTANCE.getFunction_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__PARAMS = eINSTANCE.getFunction_Params();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__COMMANDS = eINSTANCE.getFunction_Commands();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.DeclarationImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__TIPO = eINSTANCE.getDeclaration_Tipo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__NAME = eINSTANCE.getDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Asg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__ASG = eINSTANCE.getDeclaration_Asg();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.CommandImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__EXP = eINSTANCE.getCommand_Exp();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__COMMANDS = eINSTANCE.getCommand_Commands();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.ExpressionImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.RelExpImpl <em>Rel Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.RelExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getRelExp()
     * @generated
     */
    EClass REL_EXP = eINSTANCE.getRelExp();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REL_EXP__ARGS = eINSTANCE.getRelExp_Args();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REL_EXP__VAL = eINSTANCE.getRelExp_Val();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.ArithExpImpl <em>Arith Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.ArithExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getArithExp()
     * @generated
     */
    EClass ARITH_EXP = eINSTANCE.getArithExp();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.TermImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.FactorImpl <em>Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.FactorImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getFactor()
     * @generated
     */
    EClass FACTOR = eINSTANCE.getFactor();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.AtomImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.lValueImpl <em>lValue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.lValueImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getlValue()
     * @generated
     */
    EClass LVALUE = eINSTANCE.getlValue();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.PointerExpImpl <em>Pointer Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.PointerExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getPointerExp()
     * @generated
     */
    EClass POINTER_EXP = eINSTANCE.getPointerExp();

    /**
     * The meta object literal for the '<em><b>Ptr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POINTER_EXP__PTR = eINSTANCE.getPointerExp_Ptr();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.LiteralImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.LogicExpImpl <em>Logic Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.LogicExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getLogicExp()
     * @generated
     */
    EClass LOGIC_EXP = eINSTANCE.getLogicExp();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.AritmExpImpl <em>Aritm Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.AritmExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getAritmExp()
     * @generated
     */
    EClass ARITM_EXP = eINSTANCE.getAritmExp();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.UnaryExpImpl <em>Unary Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.UnaryExpImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getUnaryExp()
     * @generated
     */
    EClass UNARY_EXP = eINSTANCE.getUnaryExp();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.IDValImpl <em>ID Val</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.IDValImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getIDVal()
     * @generated
     */
    EClass ID_VAL = eINSTANCE.getIDVal();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.IntLitImpl <em>Int Lit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.IntLitImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getIntLit()
     * @generated
     */
    EClass INT_LIT = eINSTANCE.getIntLit();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LIT__VALOR = eINSTANCE.getIntLit_Valor();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.TrueLitImpl <em>True Lit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.TrueLitImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getTrueLit()
     * @generated
     */
    EClass TRUE_LIT = eINSTANCE.getTrueLit();

    /**
     * The meta object literal for the '{@link com.poli.compilador.c.impl.FalseLitImpl <em>False Lit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.poli.compilador.c.impl.FalseLitImpl
     * @see com.poli.compilador.c.impl.CPackageImpl#getFalseLit()
     * @generated
     */
    EClass FALSE_LIT = eINSTANCE.getFalseLit();

  }

} //CPackage
