/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.poli.compilador.c.Declaration#getTipo <em>Tipo</em>}</li>
 *   <li>{@link com.poli.compilador.c.Declaration#getName <em>Name</em>}</li>
 *   <li>{@link com.poli.compilador.c.Declaration#getAsg <em>Asg</em>}</li>
 * </ul>
 *
 * @see com.poli.compilador.c.CPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends Definition
{
  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see com.poli.compilador.c.CPackage#getDeclaration_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link com.poli.compilador.c.Declaration#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute list.
   * @see com.poli.compilador.c.CPackage#getDeclaration_Name()
   * @model unique="false"
   * @generated
   */
  EList<String> getName();

  /**
   * Returns the value of the '<em><b>Asg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Asg</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asg</em>' attribute.
   * @see #setAsg(String)
   * @see com.poli.compilador.c.CPackage#getDeclaration_Asg()
   * @model
   * @generated
   */
  String getAsg();

  /**
   * Sets the value of the '{@link com.poli.compilador.c.Declaration#getAsg <em>Asg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asg</em>' attribute.
   * @see #getAsg()
   * @generated
   */
  void setAsg(String value);

} // Declaration
