/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.poli.compilador.c.CPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Atom
{
} // Expression
