/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.poli.compilador.c.FieldAccess#getObj <em>Obj</em>}</li>
 *   <li>{@link com.poli.compilador.c.FieldAccess#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see com.poli.compilador.c.CPackage#getFieldAccess()
 * @model
 * @generated
 */
public interface FieldAccess extends Expression
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' containment reference.
   * @see #setObj(Expression)
   * @see com.poli.compilador.c.CPackage#getFieldAccess_Obj()
   * @model containment="true"
   * @generated
   */
  Expression getObj();

  /**
   * Sets the value of the '{@link com.poli.compilador.c.FieldAccess#getObj <em>Obj</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' containment reference.
   * @see #getObj()
   * @generated
   */
  void setObj(Expression value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Field</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' attribute.
   * @see #setField(String)
   * @see com.poli.compilador.c.CPackage#getFieldAccess_Field()
   * @model
   * @generated
   */
  String getField();

  /**
   * Sets the value of the '{@link com.poli.compilador.c.FieldAccess#getField <em>Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' attribute.
   * @see #getField()
   * @generated
   */
  void setField(String value);

} // FieldAccess
