/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>True Lit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.poli.compilador.c.TrueLit#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see com.poli.compilador.c.CPackage#getTrueLit()
 * @model
 * @generated
 */
public interface TrueLit extends Literal
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(String)
   * @see com.poli.compilador.c.CPackage#getTrueLit_Val()
   * @model
   * @generated
   */
  String getVal();

  /**
   * Sets the value of the '{@link com.poli.compilador.c.TrueLit#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(String value);

} // TrueLit
