/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.c;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Cmd</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.poli.compilador.c.VarCmd#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see com.poli.compilador.c.CPackage#getVarCmd()
 * @model
 * @generated
 */
public interface VarCmd extends Command
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference list.
   * @see com.poli.compilador.c.CPackage#getVarCmd_Val()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getVal();

} // VarCmd
