/**
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.ui;

import com.poli.compilador.ui.AbstractCUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CUiModule extends AbstractCUiModule {
  public CUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
