/*
 * generated by Xtext 2.12.0
 */
package com.poli.compilador.ide

import com.google.inject.Guice
import com.poli.compilador.CRuntimeModule
import com.poli.compilador.CStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CIdeSetup extends CStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CRuntimeModule, new CIdeModule))
	}
	
}
